language: python
cache: pip
python: "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r testrequirements.txt
  - pip install coveralls

script:
  coverage run --source='.' -m unittest discover --pattern='*_test.py'
after_success:
  coveralls


